name: Build Tools and Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: Release Version
        default: ''
        required: false
        type: string

  pull_request:
    branches:
      - main

jobs:
  # Only if this was manually triggered
  create-release:
    name: Create new release
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    outputs:
      release_version: ${{ steps.release_tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false
      - name: Release version
        id: release_tag
        run: |
          tag=$(date +%Y_%m_%d)
          if [ -n "${{ github.event.inputs.release_version }}" ]; then \
            tag=${{ github.event.inputs.release_version }}
          fi
          echo "tag=${tag}" >> $GITHUB_OUTPUT

      - name: Create new release
        run: |
          gh release create ${{ steps.release_tag.outputs.tag }} --target ${{ github.sha }} \
            --title "EDA Tool Release ${{ steps.release_tag.outputs.tag }}" \
            --notes "Various binaries for EDA tools." \
            --generate-notes
        env:
         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  check-submodule:
    name: Check for changes
    runs-on: ubuntu-latest
    needs: create-release
    if: ${{ always() }}
    outputs:
      build_slang: ${{ steps.check_submodule_slang.outputs.build }}  # Default to false if not set
      build_verilator: ${{ steps.check_submodule_verilator.outputs.build }}  # Default to false if not set
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Check for submodule changes
        id: check_submodule_slang
        run: |
          ./ci/check_submodule_change.sh slang
      - name: Check for submodule changes
        id: check_submodule_verilator
        run: |
          ./ci/check_submodule_change.sh verilator

  build-and-upload-slang:
    name: Build (and upload) `slang`
    uses: ./.github/workflows/slang.yml
    needs: [check-submodule, create-release]
    if: ${{ (always() && needs.check-submodule.outputs.build_slang == 'true') || github.event_name != 'pull_request' }}
    with:
      release_version: ${{ needs.create-release.outputs.release_version }}
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      APPLE_CERT_DATA: ${{ secrets.APPLE_CERT_DATA }}
      APPLE_CERT_PASSWORD: ${{ secrets.APPLE_CERT_PASSWORD }}
      APPLE_NOTARY_PASSWORD: ${{ secrets.APPLE_NOTARY_PASSWORD }}

  build-and-upload-verilator:
    name: Build (and upload) `verilator`
    uses: ./.github/workflows/verilator.yml
    needs: [check-submodule, create-release]
    if: ${{ (always() && needs.check-submodule.outputs.build_verilator == 'true') || github.event_name != 'pull_request' }}
    with:
      release_version: ${{ needs.create-release.outputs.release_version }}
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      APPLE_CERT_DATA: ${{ secrets.APPLE_CERT_DATA }}
      APPLE_CERT_PASSWORD: ${{ secrets.APPLE_CERT_PASSWORD }}
      APPLE_NOTARY_PASSWORD: ${{ secrets.APPLE_NOTARY_PASSWORD }}

  build-and-upload-yosys:
    name: Build (and upload) `yosys`
    uses: ./.github/workflows/yosys.yml
    needs: [create-release]
    # if: ${{ (always() && needs.check-submodule.outputs.build_verilator == 'true') || github.event_name != 'pull_request' }}
    with:
      release_version: ${{ needs.create-release.outputs.release_version }}
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      APPLE_CERT_DATA: ${{ secrets.APPLE_CERT_DATA }}
      APPLE_CERT_PASSWORD: ${{ secrets.APPLE_CERT_PASSWORD }}
      APPLE_NOTARY_PASSWORD: ${{ secrets.APPLE_NOTARY_PASSWORD }}
