name: Build Tools and Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: Release Version
        default: ''
        required: false
        type: string

  pull_request:
    branches:
      - main

env:
  APPLE_ID_NAME: Florian Zaruba
  APPLE_TEAM_ID: 4LZSA9ML57
  APPLE_ID: florian@zaruba.email

jobs:
  create-release:
    name: Update release description with version info
    runs-on: ubuntu-latest
    outputs:
      release_version: ${{ steps.release_tag.outputs.tag }}
      build-slang: ${{ steps.check_submodules.outputs.build_slang }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false
      - name: Release version
        id: release_tag
        run: |
          tag=$(date +%Y_%m_%d)
          if [ -n "${{ github.event.inputs.release_version }}" ]; then \
            tag=${{ github.event.inputs.release_version }}
          fi
          echo "tag=${tag}" >> $GITHUB_OUTPUT

      - name: Update release description
        run: |
          gh release create ${{ steps.release_tag.outputs.tag }} --target ${{ github.sha }} \
            --title "EDA Tool Release ${{ steps.release_tag.outputs.tag }}" \
            --notes "Various binaries for EDA tools." \
            --generate-notes
        env:
         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  check-submodule:
    name: Check if Submodule SHA has Changed
    runs-on: ubuntu-latest
    needs: create-release
    outputs:
      build_slang: ${{ steps.check_submodules.outputs.sha_changed || 'false' }}  # Default to false if not set
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - name: Check for submodule changes
        id: check_submodules
        run: |
          SUBMODULE_PATH="slang"
          PREV_SHA=$(git ls-tree HEAD^ $SUBMODULE_PATH | awk '{ print $3 }')  # Get previous commit's submodule SHA
          CURRENT_SHA=$(git ls-tree HEAD $SUBMODULE_PATH | awk '{ print $3 }')  # Get current commit's submodule SHA
          echo "Previous SHA: $PREV_SHA"
          echo "Current SHA: $CURRENT_SHA"

          if [ "$PREV_SHA" != "$CURRENT_SHA" ]; then
            echo "Submodule SHA has changed"
            echo "build_slang=true" >> $GITHUB_OUTPUT
          else
            echo "Submodule SHA has not changed"
            echo "build_slang=false" >> $GITHUB_OUTPUT
          fi

  build-and-upload-slang:
    uses: ./.github/workflows/slang.yml
    needs: [create-release, check-submodule]
    if: needs.create-release.outputs.build_slang == 'true'
    with:
      release_version: ${{ needs.create-release.outputs.release_version }}
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      APPLE_CERT_DATA: ${{ secrets.APPLE_CERT_DATA }}
      APPLE_CERT_PASSWORD: ${{ secrets.APPLE_CERT_PASSWORD }}
      APPLE_NOTARY_PASSWORD: ${{ secrets.APPLE_NOTARY_PASSWORD }}
