name: Build and Upload Yosys

on:
  workflow_call:
    inputs:
      release_version:
        description: "Release Version"
        required: false
        type: string
        default: ""
    secrets:
      GH_TOKEN:
        description: "Github token for release"
      APPLE_CERT_DATA:
        description: "API key for deployment"
      APPLE_CERT_PASSWORD:
        description: "Access token for secure operations"
      APPLE_NOTARY_PASSWORD:
        description: "App specific notary password"

env:
  PKG_NAME: yosys

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: amd64
            label: manylinux_2_28
            container: quay.io/pypa/manylinux_2_28_x86_64
            runner_group: production-AWS-CPU-X86_64-EKS
            runner_labels: production-scale-set-x64-8-32
          - arch: arm64
            label: manylinux_2_28
            container: quay.io/pypa/manylinux_2_28_aarch64
            runner_group: production-AWS-CPU-ARM64-EKS
            runner_labels: production-scale-set-arm64-8-16
          - arch: arm64
            label: macos
            container: ""
            runner_group: Default
            runner_labels: macos-15

    runs-on:
      group: ${{ matrix.runner_group }}
      labels: ${{ matrix.runner_labels }}
    container: ${{ matrix.container || null }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
          fetch-depth: 0

      - name: Install dependencies (Linux)
        if: ${{ matrix.container != '' }}
        run: |
          yum install -y \
            gperf bison flex gawk git pkgconfig zlib-devel zlib-static \
            clang gcc-toolset-12-gcc-c++ make wget

      - uses: maxim-lobanov/setup-xcode@v1
        if: ${{ matrix.label == 'macos' }}
        with:
          xcode-version: ^16.0.0

      - name: Set up Homebrew
        if: ${{ matrix.label == 'macos' }}
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install packages for build (macOS)
        if: ${{ matrix.label == 'macos' }}
        run: |
          brew install bison flex gawk pkg-config bash autoconf

      - name: Configure
        working-directory: ${{ env.PKG_NAME }}
        run: |
            git submodule update --init --recursive
            make config-clang ENABLE_TCL=0 ENABLE_READLINE=0 ENABLE_PLUGINS=0

      - name: Build
        working-directory: ${{ env.PKG_NAME }}
        run: |
            if [ -f /etc/redhat-release ]; then
              NPROC=$(nproc)
            else
              NPROC=$(sysctl -n hw.logicalcpu)
            fi
            make -j "$NPROC" ENABLE_TCL=0 ENABLE_READLINE=0 ENABLE_PLUGINS=0
            make install ENABLE_TCL=0 ENABLE_READLINE=0 ENABLE_PLUGINS=0 PREFIX=$(pwd)/install

      - name: Verify linking
        working-directory: ${{ env.PKG_NAME }}
        run: |
            if [ -f /etc/redhat-release ]; then
              echo "=== ldd output ==="
              ldd install/bin/yosys || true
            else
              echo "=== otool -L output ==="
              otool -L install/bin/yosys || true
            fi

      # Install yosys-slang plugin
      - name: Build yosys-slang
        working-directory: yosys-slang
        run: |
          if [ -f /etc/redhat-release ]; then
            NPROC=$(nproc)
          else
            NPROC=$(sysctl -n hw.logicalcpu)
          fi
          git submodule update --init --recursive
          make YOSYS_PREFIX=$(pwd)/../yosys/install/bin/ CXXFLAGS="-std=c++20 -I$(pwd)/../yosys" -j"$NPROC" CC=clang CXX=clang++
          cp build/slang.so $(pwd)/../yosys/install/bin/

      - name: Sign and package
        uses: ./.github/actions/package
        if: ${{ inputs.release_version != '' }}
        with:
            working_directory: ${{ env.PKG_NAME }}
            pkg_name: ${{ env.PKG_NAME }}
            matrix_arch: ${{ matrix.arch }}
            matrix_label: ${{ matrix.label }}
            release_version: ${{ inputs.release_version }}
            apple_cert_data: ${{ secrets.APPLE_CERT_DATA }}
            apple_cert_password: ${{ secrets.APPLE_CERT_PASSWORD }}
            apple_notary_password: ${{ secrets.APPLE_NOTARY_PASSWORD }}
            gh_token: ${{ secrets.GH_TOKEN  }}
